
names <- c("I","am","a","beast")
t.mat <- matrix(c(0.1,0.8,0.05,0.05,0.5,0.05,0.4,0.05,0.05,0.05,0.05,0.85,0.1,0.1,0.1,0.7), nrow=4, byrow=T)
t.mat

output <- c("am","a","I","beast")
sum(t.mat)

t.mat[grep(output[2],names,fixed=T), grep(output[1],names,fixed=T)]

perplexity(output,70,90,t.mat,names)
	
# Perplexity function takses four arguments:
# ouput vector generated by Markov Chain, range in percentage i.e.(90,100)
# a transition matrix, and vector of names which matches the rows of transition matrix 
perplexity <- function(output, range=c(start,end), matrix, words) { 
	
	#Check whether output is a vector 
	if(is.vector(output)==FALSE){
	  break()
	}
	
	n <- length(output)
	
	# Position of starting word 
	s <- round(n*(start/100))
	# Position of ending word 
	e <- round(n*(end/100))
	
	# Null vector which will store probabilities for each word from transition matrix 
	p <- vector()
	d <- e-s
	n 
	# Loop to store probabilities 
		for(i in 0:d) {
			p <- matrix[grep(output[s+i-1],words), grep(output[s+i],words)]
		}
		
		entropy <- (-1)*sum(p*log(p,base=2))
	return(2^entropy)
	
}




	